title: Charles Taylor - Portfolio
email: charlestaylor95@gmail.com
description: >-
  Check out my portfolio!
  I'm currently job seeking, for web development positions.
  I'm proficient in React.js, Django, & Ruby on rails.
  I also have great interest in less mainstream languges, namely Rust & Haskell.
Reach out to me at [charlestaylor95@gmail.com](mailto:charlestaylor95@gmail.com).
baseurl: ""
url: https://charlestaylor7.github.io/
github_username:  CharlesTaylor7
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
