title: Charles Taylor
email: charlestaylor95@gmail.com
description: >-
  I'm currently job seeking, for web development positions.
  I'm proficient in mainstream web frameworks, React.js, Django, & Ruby on rails, to name a few.
  I'm also quite proficient in less mainstream technologies, namely Rust & Haskell.
baseurl: ""
url: https://charlestaylor7.github.io/
github_username:  CharlesTaylor7
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
